name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Dependencies
        run: npm install

      - name: Add Android Platform
        run: cordova platform add android

      - name: Build Android App (Debug)
        run: cordova build android --debug

      - name: Build Android App (Release)
        run: cordova build android --release

      - name: Upload APK Artifact (Release)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: my-app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Archwiazacja pliku APK (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: my-app/platforms/android/app/build/outputs/apk/debug/app-debug.apk
          
